HickoryPTAApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HickoryPTAApp.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;

namespace HickoryPTAApp.Controllers
{
    [Authorize(Roles = AdminConstants.Roles.Administrator)]
    public class AdminController : Controller
    {
        private ICommitteeRepository _committeeRepository;
        private ApplicationUserManager _userManager;
        private ApplicationRoleManager _roleManager;

        public AdminController()
        {
        }

        public AdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? ApplicationRoleManager.Create();
            }
            private set
            {
                _roleManager = value;
            }
        }

        public ICommitteeRepository CommitteeRepository
        {
            get
            {
                if (_committeeRepository == null)
                    _committeeRepository = new CommitteeRepository();
                return _committeeRepository;
            }

            set
            {
                _committeeRepository = value;
            }
        }

        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Roles()
        {
            return View(new AdminRolesViewModel() { Roles = RoleManager.Roles });
        }

        [HttpPost]
        public async Task<ActionResult> Roles(AdminRolesViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole(model.NewRoleName);
                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First().ToString());
                    return View(model);
                }

                model.NewRoleName = String.Empty;
                model.Roles = RoleManager.Roles;
                return View(model);
            }
            else
            {
                return View(model);
            }
        }

        public ActionResult Users()
        {
            var model = new AdminUsersViewModel();
            GetUsersAndRoles(model);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Users(AdminUsersViewModel model, string[] SelectedRoles, string Command)
        {
            GetUsersAndRoles(model);

            if (Command == "Save")
            {
                foreach (var role in model.Roles)
                {
                    if (SelectedRoles != null && SelectedRoles.Contains(role.Name))
                    {
                        if (!UserManager.IsInRole(model.SelectedUserId, role.Name))
                            UserManager.AddToRole(model.SelectedUserId, role.Name);
                    }
                    else if (UserManager.IsInRole(model.SelectedUserId, role.Name))
                    {
                        UserManager.RemoveFromRole(model.SelectedUserId, role.Name);
                        if (role.Name == AdminConstants.Roles.CommitteeChair)
                        {
                            var user = model.Users.First(u => u.Id == model.SelectedUserId);
                            CommitteeRepository.RemoveMemberFromCommittes(user.Member);
                            CommitteeRepository.Save();
                        }
                    }
                }
            }

            if (ModelState.IsValid)
            {
                return View(model);
            }
            else
            {
                return View(model);
            }
        }

        private void GetUsersAndRoles(AdminUsersViewModel model)
        {
            model.Users = UserManager.Users
                .Include(u => u.Roles)
                .Include(u => u.Member)
                .OrderBy(u => u.Member.Name.First)
                .ToList();
            model.Roles = RoleManager.Roles.ToList();
        }

        // GET: Admin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

HickoryPTAApp/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PTAData.Entities;
using HickoryPTAApp.Models;

namespace HickoryPTAApp.Controllers
{
    public class NavigationController : Controller
    {
        private readonly ICommitteeRepository committeeRepository;

		// If you are using Dependency Injection, you can delete the following constructor
        public NavigationController() : this(new CommitteeRepository())
        {
            
        }

        public NavigationController(ICommitteeRepository committeeRepository)
        {
			this.committeeRepository = committeeRepository;
        }

        [ChildActionOnly]
        public ActionResult NavBar()
        {
            var navModel = new NavigationViewModel();
           
            navModel.NavigationCommittees.AddRange(
                committeeRepository
                .All
                .Select(c => new NavigationCommittee()
                {
                    CommitteeId = c.CommitteeId,
                    CommitteeName = c.CommitteeName
                }));

            return PartialView("_NavBar", navModel);
        }
    }
}

HickoryPTAApp/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PTAData.Entities;
using HickoryPTAApp.Models;
using HickoryPTAApp.Extentions;

namespace HickoryPTAApp.Controllers
{
    [Authorize(Roles = 
        AdminConstants.Roles.CommitteeChair + "," + AdminConstants.Roles.Administrator)]
    public class PostsController : Controller
    {
        private readonly IPostRepository postRepository;
        private readonly IServerFileRepository serverFileRepository;

        // If you are using Dependency Injection, you can delete the following constructor
        public PostsController()
            : this(new PostRepository(), new ServerFileRepository())
        {
        }

        public PostsController(IPostRepository postRepository, IServerFileRepository serverFileRepository)
        {
            this.postRepository = postRepository;
            this.serverFileRepository = serverFileRepository;
        }

        //
        // GET: /Posts/

        public ViewResult Index()
        {
            return View(postRepository.AllIncluding(p => p.Files));
        }

        public string CurrentUser
        {
            get
            {
                return User != null ? User.Identity.Name : "Anonymous";
            }
        }

        public ActionResult Create(string Type, string CommitteeId)
        {
            Type postType = Type == "CommitteePost" ? typeof(CommitteePost) : typeof(CommitteeEvent);
            var obj = Activator.CreateInstance(postType);
            var propInfo = postType.GetProperty("CommitteeId");
            propInfo.SetValue(obj, System.Convert.ToInt32(CommitteeId));

            var evt = obj as CommitteeEvent;
            if (evt != null)
            {
                var now = DateTime.Now;
                var eventDateDefault  = new DateTime(now.Year, now.Month, now.Day, 17, 0, 0);
                evt.EventDate = eventDateDefault;
                evt.ViewEndDate = evt.EventDate;
            }

            return View(obj);
        }

        [HttpPost]
        public ActionResult Create(CommitteePost post, CommitteeEvent evt, HttpPostedFileBase File)
        {
            return CreateOrEdit(post, evt, File);
            
        }

        private ActionResult CreateOrEdit(CommitteePost post, CommitteeEvent evt, HttpPostedFileBase File)
        {
            if (File != null)
            {
                var postFile = new PostFile();
                postFile.PostId = post.PostId;
                postFile.PostedFile = File;
                serverFileRepository.InsertOrUpdate(postFile, CurrentUser);
                serverFileRepository.Save();

                return Edit(post.PostId);
            }

            // Couldn't get the Location.LocationId key to work correctly with the hidden 
            // field so just remove it from validation. 
            ModelState.Remove("Location.LocationId");
            if (ModelState.IsValid)
            {
                if (evt.Location == null)
                {
                    return Save(post);
                }
                else
                {
                    if (evt.ViewEndDate > evt.EventDate)
                        evt.EndDate = evt.ViewEndDate;

                    return Save(evt);
                }
            }
            else
            {
                if (evt.Location == null)
                    return View(post);
                else
                    return View(evt);
            }
        }

        
        //
        // GET: /Posts/Details/5
        [AllowAnonymous]
        public ViewResult Details(int id)
        {
            return View(postRepository.Find(id));
        }

        //
        // GET: /Posts/Edit/5

        public ActionResult Edit(int id)
        {
            var post = postRepository.Find(id);

            var evt = post as CommitteeEvent;
            if (evt != null)
            {
                evt.ViewEndDate = evt.EndDate.HasValue ? evt.EndDate.Value : evt.EventDate;
            }

            return View(post);
        }

        //
        // POST: /Posts/Edit/5

        [HttpPost]
        public ActionResult Edit(CommitteePost post, CommitteeEvent evt, HttpPostedFileBase File)
        {
            return CreateOrEdit(post, evt, File);
        }

        private ActionResult Save(Post post)
        {
            // Files are save on upload. No need to send them in now.
            post.Files = null;

            postRepository.InsertOrUpdate(post, CurrentUser);
            postRepository.Save();
            var committeeId =
                post is CommitteeEvent ?
                (post as CommitteeEvent).CommitteeId :
                (post as CommitteePost).CommitteeId;
            return RedirectToAction("Edit", "Committees", new { id = committeeId });
        }


        //
        // GET: /Posts/Delete/5

        public ActionResult Delete(int id)
        {
            return View(postRepository.Find(id));
        }

        //
        // POST: /Posts/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id, string PreviousUrl)
        {
            postRepository.Delete(id);
            postRepository.Save();

            if (String.IsNullOrEmpty(PreviousUrl))
                return RedirectToAction("Index", "Home");
            else
                return Redirect(PreviousUrl);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                postRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HickoryPTAApp/Views/Shared/_BreakingNewsPartial.cshtml
@model IEnumerable<PTAData.Entities.CommitteePost>

@if (Model != null && Model.Count() > 0)
{
    <h2>Breaking News</h2>
    foreach (var post in Model)
    {
        <div class="panel panel-primary">
            <div class="panel-heading">
                <a style="color:white" data-toggle="collapse" data-parent="accordionPosts" href="#collapse@(post.PostId)">
                    <h4 style="color:white" class="panel-title">
                        @post.PostTitle - @post.Committee.CommitteeName
                    </h4>
                </a>
            </div>

            <div id="collapse@(post.PostId)" class="panel-collapse collapse in">
                <div class="panel-body">
                    <p>@post.PostBody</p>

                    @if (post.Files != null && post.Files.Any())
                    {
                        <br />
                        <div class="display-label">Attachments</div>
                        foreach (var file in post.Files)
                        {
                            <a href="@file.Path.Replace("~", String.Empty)">@file.FileName</a>
                        }
                    }
                </div>
            </div>
        </div>
    }

}

HickoryPTAApp/Views/Shared/_EventsPartial.cshtml
@model IEnumerable<PTAData.Entities.CommitteeEvent>

@if (Model != null && Model.Count() > 0)
{
    <h2>Upcoming Events</h2>
    <table class="table table-condensed">
        <thead>
            <tr>
                <td>Title</td>
                <td>Date</td>
                <td>Location</td>
                <td>Committee</td>
            </tr>
        </thead>
        <tbody>
        @foreach(var evt in Model)
        {
            <tr>
                <td>@Html.ActionLink(@evt.PostTitle, "Details", "Posts", new { id = @evt.PostId}, null)</td>
                <td>@evt.DateString()</td>
                @{ var location = evt.Location != null ? evt.Location.Name : "";}
                <td>@location</td>
                <td>@evt.Committee.CommitteeName</td>
            </tr>
        }
        </tbody>
    </table>
    
}

HickoryPTAApp/Views/Shared/_FilesPartial.cshtml
@model HickoryPTAApp.Models.FilesPartialModel

@if (Model.Files != null && Model.Files.Count() > 0)
{
    <h2>@Model.Title</h2>
    <ul>
        @foreach (var file in Model.Files)
	    {
		    <li><a href="@file.Path.Replace("~", String.Empty)">@file.FileName</a></li>
	    }
    </ul>
}

HickoryPTAApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Hickory PTA</title>
    <link rel="shortcut icon" href="~/Content/images/squirrel-20140924-favicon.ico" type="image/x-icon">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
        window.appInsights=window.appInsights||function(ai){
            function f(t){ai[t]=function(){var i=arguments;ai.queue.push(function(){ai[t].apply(ai,i)})}}
            var t=document,r="script",u=t.createElement(r),i;for(u.src=ai.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.10.js",t.getElementsByTagName(r)[0].parentNode.appendChild(u),ai.cookie=t.cookie,ai.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)f("track"+i.pop());
            return ai;
        }({
            iKey:"700f384d-6a14-4589-b289-ef0bc37222c4"
        });

        appInsights.trackPageView();
    </script>
</head>
<body>
    @Html.Action("NavBar", "Navigation")

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @Html.Partial("_SponsorsCarousel")
            <p>&copy; @DateTime.Now.Year - Hickory Elementary PTA</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/site")
    @RenderSection("scripts", required: false)
</body>
</html>

HickoryPTAApp/Views/Shared/_NavBar.cshtml
@model HickoryPTAApp.Models.NavigationViewModel

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                <img class="" style="max-height:34px; max-width:100px; margin-top: -7px;" src="~/Content/images/squirrel-small.gif" />
                Hickory PTA
            </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Committees
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu columns" role="menu">
                    @foreach (var item in Model.NavigationCommittees)
                    {
                        <li>
                            @Html.ActionLink(item.CommitteeName, "Pages", "Committees", new { id = item.CommitteeId }, null)
                        </li>
                    }
                    </ul>
                </li>

                @if (User.IsInRole(HickoryPTAApp.Models.AdminConstants.Roles.Administrator))
                {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Admin
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            @*<li>@Html.ActionLink("Roles", "Roles", "Admin")</li>*@
                            <li>@Html.ActionLink("Users", "Index", "Members")</li>
                            <li>@Html.ActionLink("Users and Roles", "Users", "Admin")</li>
                            <li>@Html.ActionLink("Committees", "Index", "Committees")</li>
                        </ul>
                    </li>
                }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

HickoryPTAApp/Views/Shared/_SponsorsCarousel.cshtml
<div id="sponsors-carousel" class="carousel slide" @*data-ride="carousel"*@>
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#sponsors-carousel" data-slide-to="0"></li>
        <li data-target="#sponsors-carousel" data-slide-to="1"></li>
        <li data-target="#sponsors-carousel" data-slide-to="2"></li>
        <li data-target="#sponsors-carousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img class="sponsorCarouselImg" src="~/Content/files/SponsorsImages/images.jpg">
            <div class="carousel-caption">
                ...
            </div>
        </div>
        <div class="item">
            <img class="sponsorCarouselImg" src="~/Content/files/SponsorsImages/star-wars-business-cards-4.jpg">
            <div class="carousel-caption">
                ...
            </div>
        </div>
        <div class="item">
            <img class="sponsorCarouselImg" src="~/Content/files/SponsorsImages/star-wars-business-cards-8.jpg">
            <div class="carousel-caption">
                ...
            </div>
        </div>
        <div class="item">
            <img class="sponsorCarouselImg" src="~/Content/files/SponsorsImages/Business-Card.png">
            <div class="carousel-caption">
                ...
            </div>
        </div>        
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#sponsors-carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#sponsors-carousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
  