HickoryPTAApp/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PTAData.Entities;
using HickoryPTAApp.Models;
using HickoryPTAApp.Extentions;

namespace HickoryPTAApp.Controllers
{
    [Authorize(Roles = 
        AdminConstants.Roles.CommitteeChair + "," + AdminConstants.Roles.Administrator)]
    public class PostsController : Controller
    {
        private readonly IPostRepository postRepository;
        private readonly IServerFileRepository serverFileRepository;

        // If you are using Dependency Injection, you can delete the following constructor
        public PostsController()
            : this(new PostRepository(), new ServerFileRepository())
        {
        }

        public PostsController(IPostRepository postRepository, IServerFileRepository serverFileRepository)
        {
            this.postRepository = postRepository;
            this.serverFileRepository = serverFileRepository;
        }

        //
        // GET: /Posts/

        public ViewResult Index()
        {
            return View(postRepository.AllIncluding(p => p.Files));
        }

        public string CurrentUser
        {
            get
            {
                return User != null ? User.Identity.Name : "Anonymous";
            }
        }

        public ActionResult Create(string Type, string CommitteeId)
        {
            Type postType = Type == "CommitteePost" ? typeof(CommitteePost) : typeof(CommitteeEvent);
            var obj = Activator.CreateInstance(postType);
            var propInfo = postType.GetProperty("CommitteeId");
            propInfo.SetValue(obj, System.Convert.ToInt32(CommitteeId));

            var evt = obj as CommitteeEvent;
            if (evt != null)
            {
                var now = DateTime.Now;
                var eventDateDefault  = new DateTime(now.Year, now.Month, now.Day, 17, 0, 0);
                evt.EventDate = eventDateDefault;
                evt.ViewEndDate = evt.EventDate;
            }

            return View(obj);
        }

        [HttpPost]
        public ActionResult Create(CommitteePost post, CommitteeEvent evt, HttpPostedFileBase File)
        {
            return CreateOrEdit(post, evt, File);
            
        }

        private ActionResult CreateOrEdit(CommitteePost post, CommitteeEvent evt, HttpPostedFileBase File)
        {
            if (File != null)
            {
                var postFile = new PostFile();
                postFile.PostId = post.PostId;
                postFile.PostedFile = File;
                serverFileRepository.InsertOrUpdate(postFile, CurrentUser);
                serverFileRepository.Save();

                return Edit(post.PostId);
            }

            // Couldn't get the Location.LocationId key to work correctly with the hidden 
            // field so just remove it from validation. 
            ModelState.Remove("Location.LocationId");
            if (ModelState.IsValid)
            {
                if (evt.Location == null)
                {
                    return Save(post);
                }
                else
                {
                    if (evt.ViewEndDate > evt.EventDate)
                        evt.EndDate = evt.ViewEndDate;

                    return Save(evt);
                }
            }
            else
            {
                if (evt.Location == null)
                    return View(post);
                else
                    return View(evt);
            }
        }

        
        //
        // GET: /Posts/Details/5
        [AllowAnonymous]
        public ViewResult Details(int id)
        {
            return View(postRepository.Find(id));
        }

        //
        // GET: /Posts/Edit/5

        public ActionResult Edit(int id)
        {
            var post = postRepository.Find(id);

            var evt = post as CommitteeEvent;
            if (evt != null)
            {
                evt.ViewEndDate = evt.EndDate.HasValue ? evt.EndDate.Value : evt.EventDate;
            }

            return View(post);
        }

        //
        // POST: /Posts/Edit/5

        [HttpPost]
        public ActionResult Edit(CommitteePost post, CommitteeEvent evt, HttpPostedFileBase File)
        {
            return CreateOrEdit(post, evt, File);
        }

        private ActionResult Save(Post post)
        {
            // Files are save on upload. No need to send them in now.
            post.Files = null;

            postRepository.InsertOrUpdate(post, CurrentUser);
            postRepository.Save();
            var committeeId =
                post is CommitteeEvent ?
                (post as CommitteeEvent).CommitteeId :
                (post as CommitteePost).CommitteeId;
            return RedirectToAction("Edit", "Committees", new { id = committeeId });
        }


        //
        // GET: /Posts/Delete/5

        public ActionResult Delete(int id)
        {
            return View(postRepository.Find(id));
        }

        //
        // POST: /Posts/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id, string PreviousUrl)
        {
            postRepository.Delete(id);
            postRepository.Save();

            if (String.IsNullOrEmpty(PreviousUrl))
                return RedirectToAction("Index", "Home");
            else
                return Redirect(PreviousUrl);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                postRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HickoryPTAApp/Controllers/ServerFilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HickoryPTAApp.Models;
using PTAData.Entities;

namespace HickoryPTAApp.Controllers
{
    [Authorize(Roles =
            AdminConstants.Roles.CommitteeChair + "," +
            AdminConstants.Roles.BoardMember + "," +
            AdminConstants.Roles.Administrator)]
    public class ServerFilesController : Controller
    {
        private HickoryPTAAppContext db = new HickoryPTAAppContext();

        // GET: ServerFiles
        public ActionResult Index()
        {
            return View(db.ServerFiles.ToList());
        }

        // GET: ServerFiles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServerFile serverFile = db.ServerFiles.Find(id);
            if (serverFile == null)
            {
                return HttpNotFound();
            }
            return View(serverFile);
        }

        // GET: ServerFiles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ServerFiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FileId,FileName,Path,LastModified,CreatedOn,UserModified")] ServerFile serverFile)
        {
            if (ModelState.IsValid)
            {
                db.ServerFiles.Add(serverFile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(serverFile);
        }

        // GET: ServerFiles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServerFile serverFile = db.ServerFiles.Find(id);
            if (serverFile == null)
            {
                return HttpNotFound();
            }
            return View(serverFile);
        }

        // POST: ServerFiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FileId,FileName,Path,LastModified,CreatedOn,UserModified")] ServerFile serverFile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(serverFile).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(serverFile);
        }

        // GET: ServerFiles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServerFile serverFile = db.ServerFiles.Find(id);
            if (serverFile == null)
            {
                return HttpNotFound();
            }
            return View(serverFile);
        }

        // POST: ServerFiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, string PreviousUrl)
        {
            ServerFile serverFile = db.ServerFiles.Find(id);
            db.ServerFiles.Remove(serverFile);
            var serverpath = Server.MapPath(serverFile.Path);
            System.IO.File.Delete(serverpath);
            db.SaveChanges();

            if (String.IsNullOrEmpty(PreviousUrl))
                return RedirectToAction("Index", "Home");
            else
                return Redirect(PreviousUrl);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HickoryPTAApp/Views/Posts/Create.cshtml
@model PTAData.Entities.Post

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginHorizontalForm()) {
    @Html.ValidationSummary(true)

		@Html.Partial("_CreateOrEdit", Model)

        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" name="Command" value="Create" class="btn btn-default" />
            </div>
        </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

HickoryPTAApp/Views/Posts/Delete.cshtml
@model PTAData.Entities.Post

@{
    ViewBag.Title = "Delete";
    ViewBag.PreviousUrl = Request.UrlReferrer;
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    @{
        var legend = Model.GetType().Name;
        legend = legend.Remove(legend.IndexOf("_"));
            }
    <legend>@legend</legend>

    <h4 class="">Title</h4>
    <p class="display-field">@Model.PostTitle</p>
    <br />
    <h4 class="display-label">Description</h4>
    <p class="display-field">@Model.PostBody</p>
    <br />
    @Html.HiddenFor(model => model.PostId)
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input class="btn btn-danger" type="submit" value="Delete" /> |
        <input hidden="hidden" name="PreviousUrl" value="@ViewBag.PreviousUrl"/>
        <a href="@ViewBag.PreviousUrl" >Back</a>
    </p>
}

HickoryPTAApp/Views/Posts/Details.cshtml
@model object
@{
    ViewBag.Title = "Post Details";
}
<h2></h2>
@{var type = Model.GetType().Name;}
@Html.DisplayFor(model => model, @type)

HickoryPTAApp/Views/Posts/Edit.cshtml
@model PTAData.Entities.Post

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginHorizontalForm()) {
    @Html.ValidationSummary(true)

		@Html.Partial("_CreateOrEdit", Model)

        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" name="Command" value="Save" class="btn btn-default" />
            </div>
        </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

HickoryPTAApp/Views/Posts/Index.cshtml
@model IEnumerable<PTAData.Entities.Post>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class ="table table-condensed">
    <tr>
        <th></th>
        <th>
            Title
        </th>
        <th>
            Files
        </th>
        <th>
            LastModified
        </th>
        <th>
            CreatedOn
        </th>
        <th>
            UserModified
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.PostId }) |
                @Html.ActionLink("Details", "Details", new { id = item.PostId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.PostId })
            </td>
            <td>
                @item.PostTitle
            </td>
            <td>
                @(item.Files == null ? "None" : item.Files.Count.ToString())
            </td>
            <td>
                @String.Format("{0:g}", item.LastModified)
            </td>
            <td>
                @String.Format("{0:g}", item.CreatedOn)
            </td>
            <td>
                @item.UserModified
            </td>
        </tr>
    }

</table>

HickoryPTAApp/Views/Posts/_CreateOrEdit.cshtml
@model object

@* This partial view defines form fields that will appear when creating and editing entities *@

@Html.EditorFor(model => model, @Model.GetType().Name)

@{
    var post = Model as PTAData.Entities.Post;
    if (post.PostId != 0)
    {
<fieldset>
    <legend>
        @Html.LabelFor(model => (model as PTAData.Entities.Post).Files, "Attached Files")
    </legend>
    @if (post.Files != null && post.Files.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <td>File Name</td>
                    <td>Actions</td>
                </tr>
            </thead>
            <tbody>
                @for (int ix = 0; ix < post.Files.Count; ix++)
                {
                    var file = post.Files[ix];
                    <tr>
                        <td>@file.FileName</td>
                        <td>
                            @Html.ActionLink("Delete", "Delete", "ServerFiles", new { id = file.FileId }, null)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</fieldset>
<div class="form-group">
    <div class="col-md-6">
        <input type="file" name="File" id="File" class="form-control" onchange="this.form.submit()" />
    </div>
</div>
    }
    }